name: Test

on:
  push:
  pull_request:

jobs:


  action:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - windows
    runs-on: ${{ matrix.os }}-latest
    steps:

    - uses: actions/checkout@v2

    - shell: bash
      run: |
        echo "$ACTIONS_CACHE_URL"

    - name: Run VUnit tests
      uses: ./
      with:
        cmd: test/run.py


  action-image:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - windows
        image:
          - ''
          - 'ghdl/vunit:llvm'
    runs-on: ${{ matrix.os }}-latest
    steps:

    - uses: actions/checkout@v2

    - name: Run VUnit tests
      uses: ./
      with:
        cmd: test/run.py
        image: ${{ matrix.image }}


  container-job:
    runs-on: ubuntu-latest
    container: ghdl/vunit:mcode-master
    steps:

    - uses: actions/checkout@v2

    - run: test/run.py


  container-step:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - uses: docker://ghdl/vunit:mcode-master
      with:
        args: test/run.py
